obj-$(CONFIG_DRM_PANEL_LONGCHEER_TRULY_R63350) += panel-longcheer-truly-r63350.o
obj-$(CONFIG_DRM_PANEL_XIAOMI_KENZO_NT35532_BOE) += panel-xiaomi-kenzo-nt35532-boe.o
obj-$(CONFIG_DRM_PANEL_XIAOMI_KENZO_NT35596_TIANMA) += panel-xiaomi-kenzo-nt35596-tianma.o
obj-$(CONFIG_DRM_PANEL_XIAOMI_KENZO_R63315_SHARP) += panel-xiaomi-kenzo-r63315-sharp.o
